[update]
tasks = ["interfaces", "code", "transform", "normalize"]

[update.interfaces]
path = "XXTExplorer"
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePath = "XXTExplorer"
localizablePath = "."
defaultToKeys = false
additive = true
unstripped = false

[update.transform]
codePath = "XXTExplorer"
localizablePath = "."
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "XXTExplorer"
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "XXTExplorer"
duplicateKeys = true
emptyValues = true
