# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# cache: cocoapods
osx_image: xcode9.1
language: objective-c
podfile: Podfile

before_install:
- pod repo update
- pod install --verbose
# - gem install cocoapods # Since Travis is not always on latest version

script:
- set -o pipefail && xcodebuild build -workspace XXTExplorer.xcworkspace -scheme XXTExplorer-Archive -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
